<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ahuang_lorem_ipsum.ahuang_ipsum_api_controller' shared service.

return $this->services['ahuang_lorem_ipsum.ahuang_ipsum_api_controller'] = new \Ahuang\LoremIpsumBundle\Controller\IpsumApiController(($this->services['ahuang_lorem_ipsum.ahuang_ipsum'] ?? $this->load('getAhuangLoremIpsum_AhuangIpsumService.php')));
