<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKyxx9xR\ControllerAhuangLoremIpsumControllerKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKyxx9xR/ControllerAhuangLoremIpsumControllerKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerKyxx9xR.legacy');

    return;
}

if (!\class_exists(ControllerAhuangLoremIpsumControllerKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerKyxx9xR\ControllerAhuangLoremIpsumControllerKernelTestDebugContainer::class, ControllerAhuangLoremIpsumControllerKernelTestDebugContainer::class, false);
}

return new \ContainerKyxx9xR\ControllerAhuangLoremIpsumControllerKernelTestDebugContainer([
    'container.build_hash' => 'Kyxx9xR',
    'container.build_id' => '8a27cd94',
    'container.build_time' => 1636909792,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKyxx9xR');
