# config/routes.yaml
ahuang_lorem_ipsum_api:
    path: /
    # the controller value has the format 'controller_class::method_name'
    controller: ahuang_lorem_ipsum.ahuang_ipsum_api_controller::index