# config/services.yaml
services:
    # explicitly configure the service
    ahuang_lorem_ipsum.ahuang_ipsum:
      class: Ahuang\LoremIpsumBundle\KnpUIpsum
      public: true
      arguments:
        # - '@ahuang_lorem_ipsum.ahuang_word_provider'
        - '@ahuang_lorem_ipsum.word_provider'



    ahuang_lorem_ipsum.ahuang_word_provider:
      class: Ahuang\LoremIpsumBundle\AhuangWordProvider
      public: false

    # Ahuang\LoremIpsumBundle\KnpUIpsum: '@ahuang_lorem_ipsum.ahuang_ipsum'

    Ahuang\LoremIpsumBundle\KnpUIpsum: '@ahuang_lorem_ipsum.ahuang_ipsum'
    ahuang_lorem_ipsum.word_provider: '@ahuang_lorem_ipsum.ahuang_word_provider'