<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ahuang_lorem_ipsum.ahuang_ipsum' shared service.

return $this->services['ahuang_lorem_ipsum.ahuang_ipsum'] = new \Ahuang\LoremIpsumBundle\KnpUIpsum(new \Ahuang\LoremIpsumBundle\KnpUWordProvider(), true, 3);
