<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQDSLiB2\ControllerAhuangLoremIpsumControllerKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQDSLiB2/ControllerAhuangLoremIpsumControllerKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerQDSLiB2.legacy');

    return;
}

if (!\class_exists(ControllerAhuangLoremIpsumControllerKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerQDSLiB2\ControllerAhuangLoremIpsumControllerKernelTestDebugContainer::class, ControllerAhuangLoremIpsumControllerKernelTestDebugContainer::class, false);
}

return new \ContainerQDSLiB2\ControllerAhuangLoremIpsumControllerKernelTestDebugContainer([
    'container.build_hash' => 'QDSLiB2',
    'container.build_id' => '56a6c8d2',
    'container.build_time' => 1636909961,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQDSLiB2');
