<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSBPogvW\testsAhuang_LoremIpsumBundle_Tests_AhuangLoremIpsumTestKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSBPogvW/testsAhuang_LoremIpsumBundle_Tests_AhuangLoremIpsumTestKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerSBPogvW.legacy');

    return;
}

if (!\class_exists(testsAhuang_LoremIpsumBundle_Tests_AhuangLoremIpsumTestKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerSBPogvW\testsAhuang_LoremIpsumBundle_Tests_AhuangLoremIpsumTestKernelTestDebugContainer::class, testsAhuang_LoremIpsumBundle_Tests_AhuangLoremIpsumTestKernelTestDebugContainer::class, false);
}

return new \ContainerSBPogvW\testsAhuang_LoremIpsumBundle_Tests_AhuangLoremIpsumTestKernelTestDebugContainer([
    'container.build_hash' => 'SBPogvW',
    'container.build_id' => '0304ac02',
    'container.build_time' => 1636902999,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSBPogvW');
